version: '3'

services:
  xnode1:
    image: xnode:latest
    container_name: xnode1
    environment:
      - XNODE_NAME=Xnode-1
      - XNODE_GOSSIP_PORT=9091
      - XNODE_GOSSIP_PEERS=192.168.1.111:9092,192.168.1.112:9093
      - XNODE_IP=192.168.1.110
    networks:
      xnode-network:
        ipv4_address: 192.168.1.110
  xnode2:
    image: xnode:latest
    container_name: xnode2
    environment:
      - XNODE_NAME=Xnode-2
      - XNODE_GOSSIP_PORT=9092
      - XNODE_GOSSIP_PEERS=192.168.1.110:9091,192.168.1.114:9095
      - XNODE_IP=192.168.1.111
    networks:
      xnode-network:
        ipv4_address: 192.168.1.111
  xnode3:
    image: xnode:latest
    container_name: xnode3
    environment:
      - XNODE_NAME=Xnode-3
      - XNODE_GOSSIP_PORT=9093
      - XNODE_GOSSIP_PEERS=192.168.1.110:9091,192.168.1.111:9092
      - XNODE_IP=192.168.1.112
    networks:
      xnode-network:
        ipv4_address: 192.168.1.112
  xnode4:
    image: xnode:latest
    container_name: xnode4
    environment:
      - XNODE_NAME=Xnode-4
      - XNODE_GOSSIP_PORT=9094
      - XNODE_GOSSIP_PEERS=192.168.1.112:9093
      - XNODE_IP=192.168.1.113
    networks:
      xnode-network:
        ipv4_address: 192.168.1.113
  xnode5:
    image: xnode:latest
    container_name: xnode5
    environment:
      - XNODE_NAME=Xnode-5
      - XNODE_GOSSIP_PORT=9095
      - XNODE_GOSSIP_PEERS=192.168.1.113:9094,192.168.1.111:9092
      - XNODE_IP=192.168.1.114
    networks:
      xnode-network:
        ipv4_address: 192.168.1.114
  xnode6:
    image: xnode:latest
    container_name: xnode6
    environment:
      - XNODE_NAME=Xnode-6
      - XNODE_GOSSIP_PORT=9096
      - XNODE_GOSSIP_PEERS=192.168.1.114:9095,192.168.1.113:9094,192.168.1.111:9092,192.168.1.114:9095
      - XNODE_IP=192.168.1.115
    networks:
      xnode-network:
        ipv4_address: 192.168.1.115

networks:
  xnode-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "192.168.1.0/24"
